name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build Firmware
        uses: ./
        with:
          keymap-path: "keyboards/crkbd/keymaps/via"
          keyboard: "crkbd/rev1"
          keymap: "via"

      - name: Upload a Firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: build
